### ISSUE TITLE
Version Issues again

### ISSUE THREAD

**Issue by frugecn** [dougbw/pwsh-terrafun#3]
Looks like Hashicorp added the '/'s back in.  I'm wondering if you update the regex to allow optional ending slash.  I'm guessing something like this?

`
'^\/terraform\/[0-9]+\.[0-9]+\.[0-9]+[\/]*$'
`

**Comment by dougbw** [comment]
I suspect hashicorp are changing this intentionally to encourage people to stop scraping that page and use the new releases API (https://www.hashicorp.com/blog/announcing-the-hashicorp-releases-api) which was recently made available. I will push an update which integrates with their API as it will be less likely to run into breaking changes (hopefully!).
